### ISSUE TITLE
nodejs require > imports not defined

### ISSUE THREAD

**Issue by a2nt** [cgjs/cgjs#8]
I'd like to include cgjs into application to display panel icon, so I have following code:

`const cgjs = require('cgjs');`

After that I'm getting an error:
```
A JavaScript error occurred in the main process
Uncaught Exception:
ReferenceError: imports is not defined
    at Object.<anonymous> (/home/tony/Downloads/museeks/node_modules/cgjs/cg.js:84:4)
    at Object.<anonymous> (/home/tony/Downloads/museeks/node_modules/cgjs/cg.js:86:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/tony/Downloads/museeks/src/main-process/integrations/linux.js:5:14)

```

**Comment by WebReflection** [comment]
I think you kinda missed the whole point of this project, which is to make GJS development more friendly for node developers, not vice versa.

This is not gtk for node and it cannot be required by node.

You can use cgjs as executable *instead of* using node and some code might just work out of the box.

This might be clearer on the README though.

**Comment by a2nt** [comment]
Well do u have an example how to create an icon at the panel using cgjs -e ''; and add launch a command onclick?
I have tried: cgjs -e 'log(imports.ui)'  No JS module 'ui' found in search path

**Comment by WebReflection** [comment]
you need to use GJS, here some example (slightly outdated):
https://github.com/optimisme/gjs-examples

**Comment by a2nt** [comment]
@WebReflection thx
